from __future__ import annotations

import argparse
import os

from tuna_core.services.analysis import ANALYSIS_FIXTURE_SCENARIOS


def _env_default(name: str, fallback: str) -> str:
    return os.environ.get(name, fallback)


def _add_json(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    return parser


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Tuna Core helper tool for durable Tuna state")
    parser.add_argument("--db", default=_env_default("TUNA_DB", "tuna.sqlite3"), help="SQLite Tuna database path (default: $TUNA_DB or tuna.sqlite3)")
    top = parser.add_subparsers(dest="area", required=True)
    _add_state_commands(top)
    _add_analysis_commands(top)
    _add_workflow_commands(top)
    _add_operator_commands(top)
    _add_json(top.add_parser("status"))
    return parser


def _add_state_commands(top: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    db = top.add_parser("db")
    _add_json(db.add_subparsers(dest="action", required=True).add_parser("init"))

    build = top.add_parser("build")
    build_sub = build.add_subparsers(dest="action", required=True)
    build_create = build_sub.add_parser("create")
    build_create.add_argument("name")
    build_create.add_argument("--fc-snapshot-json", default="{}")
    build_create.add_argument("--operator-notes", default="")
    _add_json(build_create)
    _add_json(build_sub.add_parser("list"))
    build_show = build_sub.add_parser("show")
    build_show.add_argument("--build-id", type=int, required=True)
    _add_json(build_show)

    loop = top.add_parser("loop")
    loop_sub = loop.add_subparsers(dest="action", required=True)
    loop_create = loop_sub.add_parser("create")
    loop_create.add_argument("--build-id", type=int, required=True)
    loop_create.add_argument("--tune-goal", required=True)
    _add_json(loop_create)
    loop_list = loop_sub.add_parser("list")
    loop_list.add_argument("--build-id", type=int)
    _add_json(loop_list)
    loop_context = loop_sub.add_parser("context")
    loop_context.add_argument("--loop-id", type=int, required=True)
    loop_context.add_argument("--recent-limit", type=int, default=5)
    _add_json(loop_context)
    loop_status = loop_sub.add_parser("status")
    loop_status.add_argument("--loop-id", type=int, required=True)
    _add_json(loop_status)

    log = top.add_parser("log")
    log_sub = log.add_subparsers(dest="action", required=True)
    log_import = log_sub.add_parser("import")
    log_import.add_argument("path")
    log_import.add_argument("--build-id", type=int, required=True)
    log_import.add_argument("--loop-id", type=int)
    log_import.add_argument("--storage-dir", default=_env_default("TUNA_LOG_STORAGE_DIR", "tuna-data/blackbox-logs"), help="managed Blackbox Log storage directory (default: $TUNA_LOG_STORAGE_DIR or tuna-data/blackbox-logs)")
    log_import.add_argument("--full-metadata", action="store_true", help="include full parsed Blackbox metadata in JSON output")
    log_import.add_argument("--metadata-json-file", help="write full parsed Blackbox metadata to a file")
    _add_json(log_import)
    log_list = log_sub.add_parser("list")
    log_list.add_argument("--build-id", type=int)
    _add_json(log_list)


def _add_analysis_commands(top: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    analysis = top.add_parser("analysis")
    sub = analysis.add_subparsers(dest="action", required=True)
    decode = sub.add_parser("decode")
    decode.add_argument("--log-id", type=int, required=True)
    decode.add_argument("--output-dir", default=_env_default("TUNA_DECODED_LOG_DIR", "tuna-data/decoded-logs"), help="decoded CSV output directory (default: $TUNA_DECODED_LOG_DIR or tuna-data/decoded-logs)")
    decode.add_argument("--decoder-command", default=_env_default("TUNA_BLACKBOX_DECODER", "blackbox_decode"), help="Blackbox decoder command (default: $TUNA_BLACKBOX_DECODER or blackbox_decode)")
    _add_json(decode)

    analyze = sub.add_parser("analyze")
    analyze.add_argument("--log-id", type=int, required=True)
    analyze.add_argument("--csv-path")
    analyze.add_argument("--output-json-file", help="write the full analysis JSON to a file and keep CLI JSON concise")
    analyze.add_argument("--full-json", action="store_true", help="print the full analysis JSON to stdout")
    _add_json(analyze)

    decode_analyze = sub.add_parser("decode-analyze")
    decode_analyze.add_argument("--log-id", type=int, required=True)
    decode_analyze.add_argument("--output-dir", default=_env_default("TUNA_DECODED_LOG_DIR", "tuna-data/decoded-logs"), help="decoded CSV output directory (default: $TUNA_DECODED_LOG_DIR or tuna-data/decoded-logs)")
    decode_analyze.add_argument("--decoder-command", default=_env_default("TUNA_BLACKBOX_DECODER", "blackbox_decode"), help="Blackbox decoder command (default: $TUNA_BLACKBOX_DECODER or blackbox_decode)")
    decode_analyze.add_argument("--output-json-file", help="write the full analysis JSON to a file and keep CLI JSON concise")
    decode_analyze.add_argument("--full-json", action="store_true", help="print the full analysis JSON to stdout")
    _add_json(decode_analyze)

    fixture = sub.add_parser("record-fixture")
    fixture.add_argument("--log-id", type=int, required=True)
    fixture_source = fixture.add_mutually_exclusive_group(required=True)
    fixture_source.add_argument("--analysis-json-file", help="record supplied analysis JSON for no-hardware workflow tests")
    fixture_source.add_argument("--scenario", choices=ANALYSIS_FIXTURE_SCENARIOS, help="record a named fake analysis scenario for exploratory no-hardware workflow testing")
    fixture.add_argument("--full-json", action="store_true", help="print the full analysis JSON to stdout")
    _add_json(fixture)

    summary = sub.add_parser("summary")
    summary.add_argument("--log-id", type=int, required=True)
    _add_json(summary)
    segment_rows = sub.add_parser("segment-rows")
    segment_rows.add_argument("--log-id", type=int, required=True)
    segment_rows.add_argument("--segment-kind", required=True, choices=["high_rate", "throttle_punch", "throttle_chop", "propwash", "chirp"])
    segment_rows.add_argument("--segment-index", type=int, required=True)
    segment_rows.add_argument("--fields", help="comma-separated decoded CSV fields to return")
    segment_rows.add_argument("--pad-rows", type=int, default=0)
    segment_rows.add_argument("--max-rows", type=int, default=500)
    _add_json(segment_rows)
    recordings = sub.add_parser("recordings", aliases=["list-recordings"])
    recordings.add_argument("--log-id", type=int, required=True)
    recordings.add_argument("--sort", choices=["decoded", "start-time", "activity"], default="decoded")
    recordings.add_argument("--limit", type=int)
    _add_json(recordings)
    compare = sub.add_parser("compare")
    compare.add_argument("--before-log-id", type=int, required=True)
    compare.add_argument("--after-log-id", type=int, required=True)
    _add_json(compare)
    for name in ("throttle-chop", "cross-axis-flip", "noise-peaks", "propwash"):
        event_parser = sub.add_parser(name)
        event_parser.add_argument("--log-id", type=int, required=True)
        event_parser.add_argument("--limit", type=int, default=5)
        _add_json(event_parser)
    for name in ("filter-evidence", "pid-response", "rpm-filter", "capture-plan"):
        evidence_parser = sub.add_parser(name)
        evidence_parser.add_argument("--log-id", type=int, required=True)
        _add_json(evidence_parser)


def _add_workflow_commands(top: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    iteration = top.add_parser("iteration")
    sub = iteration.add_subparsers(dest="action", required=True)
    create = sub.add_parser("create")
    create.add_argument("--loop-id", type=int, required=True)
    create.add_argument("--log-id", type=int, action="append", default=[])
    _add_json(create)
    current = sub.add_parser("current")
    current.add_argument("--loop-id", type=int, required=True)
    _add_json(current)
    no_change = sub.add_parser("complete-no-change")
    no_change.add_argument("--iteration-id", type=int, required=True)
    no_change.add_argument("--reason", required=True)
    _add_json(no_change)
    with_diagnosis = sub.add_parser("complete-with-diagnosis")
    with_diagnosis.add_argument("--iteration-id", type=int, required=True)
    with_diagnosis.add_argument("--body", required=True)
    with_diagnosis.add_argument("--reason", required=True)
    with_diagnosis.add_argument("--confidence", default="")
    with_diagnosis.add_argument("--evidence-json", default="{}")
    with_diagnosis.add_argument("--result", choices=("no_change",), default="no_change")
    _add_json(with_diagnosis)

    diagnosis = top.add_parser("diagnosis")
    diagnosis_record = diagnosis.add_subparsers(dest="action", required=True).add_parser("record")
    diagnosis_record.add_argument("--iteration-id", type=int, required=True)
    diagnosis_record.add_argument("--body", required=True)
    diagnosis_record.add_argument("--confidence", default="")
    diagnosis_record.add_argument("--evidence-json", default="{}")
    _add_json(diagnosis_record)

    update = top.add_parser("update")
    update_sub = update.add_subparsers(dest="action", required=True)
    _add_json(update_sub.add_parser("pending-writes"))
    propose = update_sub.add_parser("propose")
    propose.add_argument("--iteration-id", type=int, required=True)
    propose.add_argument("--build-id", type=int, required=True)
    propose.add_argument("--settings-json", required=True)
    propose.add_argument("--cli-text", default="")
    _add_json(propose)
    for action in ("approve-for-write", "apply"):
        parser = update_sub.add_parser(action)
        parser.add_argument("--update-id", type=int, required=True)
        _add_json(parser)
    fail = update_sub.add_parser("record-write-failure")
    fail.add_argument("--update-id", type=int, required=True)
    fail.add_argument("--failure", required=True)
    _add_json(fail)
    reject = update_sub.add_parser("reject")
    reject.add_argument("--update-id", type=int, required=True)
    reject.add_argument("--reason", required=True)
    _add_json(reject)


def _add_operator_commands(top: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    task = top.add_parser("task")
    task_sub = task.add_subparsers(dest="action", required=True)
    create = task_sub.add_parser("create")
    create.add_argument("--kind", required=True)
    create.add_argument("--title", required=True)
    create.add_argument("--body", default="")
    create.add_argument("--payload-json", default="{}")
    _add_json(create)
    flight = task_sub.add_parser("request-flight-capture")
    flight.add_argument("--build-id", type=int)
    flight.add_argument("--loop-id", type=int)
    flight.add_argument("--reason", default="Need another Blackbox Log for tuning evidence.")
    flight.add_argument("--capture-goal", default="Capture a useful follow-up Blackbox Log for the current Tune Goal.")
    _add_json(flight)
    fcs = task_sub.add_parser("request-fcs-connection")
    fcs.add_argument("--build-id", type=int)
    fcs.add_argument("--loop-id", type=int)
    fcs.add_argument("--bridge-host", default=_env_default("FCS_BRIDGE_HOST", "tuna-bridge-usb"), help="FCS Bridge host to ask the Operator to restore (default: $FCS_BRIDGE_HOST or tuna-bridge-usb)")
    fcs.add_argument("--reason", default="FCS Bridge connection is required before the Tuning Agent can continue.")
    fcs.add_argument("--next-step", default="Restore the FC/Bridge connection in USB CDC/MSP mode.")
    _add_json(fcs)
    build = task_sub.add_parser("confirm-build")
    build.add_argument("--fc-snapshot-json", required=True)
    build.add_argument("--candidate-build-id", type=int)
    build.add_argument("--loop-id", type=int)
    build.add_argument("--reason", default="")
    _add_json(build)
    goal = task_sub.add_parser("request-tune-goal")
    goal.add_argument("--build-id", type=int)
    goal.add_argument("--reason", default="Define the Tune Goal before starting a Loop.")
    _add_json(goal)
    listing = task_sub.add_parser("list")
    listing.add_argument("--status", choices=("open", "resolved", "all"), default="all")
    listing.add_argument("--limit", type=int)
    _add_json(listing)
    show = task_sub.add_parser("show")
    show.add_argument("--task-id", type=int, required=True)
    _add_json(show)

    notify = top.add_parser("notification", aliases=["notify"])
    notify_sub = notify.add_subparsers(dest="action", required=True)
    blackbox = notify_sub.add_parser("blackbox-config-changed")
    blackbox.add_argument("--build-id", type=int)
    blackbox.add_argument("--loop-id", type=int)
    blackbox.add_argument("--settings-json", required=True)
    blackbox.add_argument("--previous-settings-json", default="{}")
    blackbox.add_argument("--reason", required=True)
    blackbox.add_argument("--impact", default="")
    _add_json(blackbox)
    listing = notify_sub.add_parser("list")
    listing.add_argument("--status", choices=("open", "acknowledged", "all"), default="all")
    listing.add_argument("--limit", type=int)
    _add_json(listing)
